{% set name = "phylophlan" %}
{% set version = "3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # url: https://github.com/biobakery/MetaPhlAn/archive/{{version}}.tar.gz
  # sha256: 6249bf67f9e5a1a1264020bb0de689a17402606ada8134fb09ab416981d4a48b
  # git_url: https://github.com/biobakery/MetaPhlAn.git
  # git_rev: 32b32d5e8618acf88901a536428405dbb4f3be0b
  path: ..

build:
  noarch: python
  #number: 0  Need this for Bioconda, uncomment before pushing to bioconda-recipes
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - python >=3.7
    - pip
    - biopython >=1.73
    - dendropy >=4.4.0
    - matplotlib >=3.1.0
    - numpy >=1.15.4
    - pandas >=0.24.2
    - seaborn >=0.9.0

  run:
    - python >=3.7
    - biopython >=1.73
    - dendropy >=4.4.0
    - matplotlib >=3.1.0
    - numpy >=1.15.4
    - pandas >=0.24.2
    - seaborn >=0.9.0
    - blast >=2.6.0
    - diamond >=0.9
    - trimal >=1.4.1
    - muscle >=3.8.1551
    - mafft >=7.310
    - fasttree >=2.1.8
    - raxml >=8.2.10
    - iqtree >=1.6.6

test:
  commands:
    - phylophlan --version
    - phylophlan_draw_metagenomic --version
    - phylophlan_get_reference --version
    - phylophlan_metagenomic --version
    - phylophlan_setup_database --version
    - phylophlan_strain_finder --version
    - phylophlan_write_config_file --version

about:
  home: https://github.com/biobakery/phylophlan
  license: MIT License
  license_family: MIT
  license_file: license.txt
  summary: Precise phylogenetic analysis of microbial isolates and genomes from metagenomes
  description: |
    PhyloPhlAn 3.0 is an integrated pipeline for large-scale phylogenetic 
    profiling of genomes and metagenomes. PhyloPhlAn 3.0 is an accurate, rapid,
    and easy-to-use method for large-scale microbial genome characterization 
    and phylogenetic analysis at multiple levels of resolution. PhyloPhlAn 3.0 
    can assign both genomes and metagenome-assembled genomes (MAGs) to 
    species-level genome bins (SGBs). PhyloPhlAn 3.0 can reconstruct 
    strain-level phylogenies using clade-specific maximally informative 
    phylogenetic markers, and can also scale to very-large phylogenies 
    comprising >17,000 microbial species.
